spring:
  application:
    name: community-residence-service
  profiles:
    active: dev
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
